from selenium import webdriver
import time
from selenium.webdriver.support.ui import Select

driver = webdriver.Chrome(executable_path="G:\\chromedriver\\chromedriver.exe")
Url = "https://app2.qca-dev.com/"


def login():
    driver.get(Url)
    time.sleep(5)
    driver.find_element_by_class_name("logo").click()
    driver.maximize_window()
    time.sleep(5)
    driver.find_element_by_id("username").send_keys("naveeeed.ariff@gmail.com")
    driver.find_element_by_id("password").send_keys("Test123##")
    driver.find_element_by_id("showHidePassword").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='profile_form']/div[3]/div/div/div/input").click()
    time.sleep(10)


def ask_page():
    driver.find_element_by_class_name("logo").click()
    time.sleep(10)
    driver.find_element_by_id("askanotherquestion").send_keys("List of opps")
    driver.find_element_by_class_name("chatsendbtn").click()
    time.sleep(10)
    driver.find_element_by_xpath("//*[@id='scrolltotop']/img").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='scrolltobottom']/img").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='wrapper']/nav/div/ul/li[1]/div/label/span[1]").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='wrapper']/nav/div/ul/li[1]/div/label/span[1]").click()
    time.sleep(5)
    driver.find_element_by_class_name("menubars").click()
    driver.find_element_by_xpath("//*[@id='side-menu']/li[4]/a").click()  # Settings page
    time.sleep(10)


def settings_page():
    driver.find_element_by_xpath("//*[@id='wrapper']/nav/div/ul/li[1]/div/label/span[1]").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='wrapper']/nav/div/ul/li[1]/div/label/span[1]").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='profile_form']/div/div/div[2]/div[1]/a/h3").click()
    drop = Select(driver.find_element_by_id("clearData"))
    drop.select_by_index(2)
    driver.find_element_by_class_name("cleardashboard").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='accordion2']/div/div[1]/a/h3").click()
    time.sleep(10)
    driver.find_element_by_xpath("//*[@id='isNullToZero']").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='profile_form']/div/div/div[6]/div[1]/a/h3").click()
    drop = Select(driver.find_element_by_id("showSql"))
    drop.select_by_visible_text("Yes")
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='profile_form']/div/div/div[8]/div[1]/a/h3").click()
    drop = Select(driver.find_element_by_id("showParaphrase"))
    drop.select_by_visible_text("Yes")
    time.sleep(5)
    driver.find_element_by_class_name("smallbtn1").click()
    time.sleep(5)
    driver.find_element_by_id("scrolltobottom").click()
    time.sleep(5)
    driver.find_element_by_id("scrolltotop").click()
    time.sleep(10)


def feedback_page():
    driver.find_element_by_id("scrolltobottom").click()
    time.sleep(5)
    driver.find_element_by_id("scrolltotop").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='wrapper']/nav/div/ul/li[1]/div/label/span[1]").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='wrapper']/nav/div/ul/li[1]/div/label/span[1]").click()
    time.sleep(5)
    driver.find_element_by_id("subject").send_keys("Question Error")
    time.sleep(5)
    driver.find_element_by_id("message").send_keys("List of opps is an error question")
    time.sleep(5)
    driver.find_element_by_id("filename").send_keys("G:/Naveed.jpeg")
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='profile_form']/div[8]/div/div/input").submit()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='wrapper']/div[1]/div").click()
    driver.find_element_by_xpath("//*[@id='side-menu']/span[3]/li[2]/a").click()
    driver.find_element_by_xpath("//*[@id='custAdminCollapse']/li[1]/a").click()
    time.sleep(5)


def custadmin_page():
    driver.find_element_by_xpath("//*[@id='wrapper']/nav/div/ul/li[1]/div/label/span[1]").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='wrapper']/nav/div/ul/li[1]/div/label/span[1]").click()
    time.sleep(5)
    driver.find_element_by_class_name("smallbtn1").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='wrapper']/nav/div/ul/li[1]/div/label/span[1]").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='wrapper']/nav/div/ul/li[1]/div/label/span[1]").click()
    time.sleep(5)
    # driver.find_element_by_id("firstName").send_keys("Muhammad")
    # time.sleep(5)
    # driver.find_element_by_id("lastName").send_keys("Naveed")
    # time.sleep(5)
    # driver.find_element_by_id("phone").send_keys("03228872222")
    # time.sleep(5)
    # driver.find_element_by_tag_name("Save").submit()
    # time.sleep(5)


def questionlogs_page():
    driver.find_element_by_xpath("//*[@id='wrapper']/div[1]/div").click()
    driver.find_element_by_xpath("//*[@id='side-menu']/span[3]/li[2]/a").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='custAdminCollapse']/li[2]/a").click()
    time.sleep(10)
    driver.find_element_by_xpath("//*[@id='wrapper']/nav/div/ul/li[1]/div/label/span[1]").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='wrapper']/nav/div/ul/li[1]/div/label/span[1]").click()
    time.sleep(5)
    drop = Select(driver.find_element_by_xpath("//*[@id='page-wrapper']/section[2]/div/div/div/div[1]/div[2]/select"))
    drop.select_by_index(1)
    time.sleep(10)
    driver.find_element_by_xpath("//*[@id='wrapper']/nav/div/ul/li[1]/div/label/span[1]").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='wrapper']/nav/div/ul/li[1]/div/label/span[1]").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='myTable']/tbody/tr[1]/td[5]/button").click()
    time.sleep(5)
    driver.find_element_by_class_name("close").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='wrapper']/div[1]/div").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='side-menu']/li[7]/div/div[2]/a[1]").click()
    time.sleep(10)


def myprofile_page():
    driver.find_element_by_xpath("//*[@id='wrapper']/nav/div/ul/li[1]/div/label/span[1]").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='wrapper']/nav/div/ul/li[1]/div/label/span[1]").click()
    time.sleep(5)
    driver.find_element_by_class_name("fileuploadbtn").send_keys("G:/Naveed.jpeg")
    driver.find_element_by_class_name("firstname").clear()
    driver.find_element_by_class_name("firstname").send_keys("Muhammad")
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='profile_form']/div/div[3]/div[4]/div/input").send_keys("QA Engineer")
    driver.find_element_by_class_name("company").clear()
    time.sleep(5)
    driver.find_element_by_class_name("company").send_keys("Quario")
    driver.find_element_by_class_name("phone").clear()
    time.sleep(5)
    driver.find_element_by_class_name("phone").send_keys("03228872222")
    driver.find_element_by_class_name("smallbtn1").submit()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='wrapper']/div[1]/div").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='side-menu']/li[7]/div/div[2]/a[2]").click()
    time.sleep(10)


def mypassword_page():
    driver.find_element_by_xpath("//*[@id='wrapper']/nav/div/ul/li[1]/div/label/span[1]").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='wrapper']/nav/div/ul/li[1]/div/label/span[1]").click()
    time.sleep(5)
    driver.find_element_by_id("currentPassword").send_keys("Test123##")
    time.sleep(5)
    driver.find_element_by_id("password").send_keys("Nav@123")
    driver.find_element_by_id("reEnterPassword").send_keys("Nav@123")
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='profile_form']/div[4]/input").submit()
    time.sleep(5)


def logout():
    driver.find_element_by_xpath("//*[@id='wrapper']/nav/div/ul/li[2]/a").click()
    time.sleep(10)
    driver.quit()


login()
ask_page()
settings_page()
feedback_page()
custadmin_page()
questionlogs_page()
myprofile_page()
mypassword_page()
logout()
